apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  restartPolicy: OnFailure
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        #image: image-registry.openshift-image-registry.svc:5001/app-test/nginx
        image: registry.redhat.io/rhel9/nginx-120
        #image: docker.io/nginx
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
          periodSeconds: 1
          failureThreshold: 1

