apiVersion: v1
kind: Service
metadata:https://github.com/makobaya/RedHat-usage/blob/main/nodeport.yaml
  name: nginx-service
  labels:
    app: nginx
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 80
    nodePort: 30080
    protocol: TCP
  selector:
    app: nginx

